name: deploy

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: docker/setup-qemu-action@v3
      # - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/configure-aws-credentials@v4
        if: github.event_name != 'pull_request'
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ vars.IMAGE_REPOSITORY }}
      - uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./website
